# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CombinePdfsData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'test': 'bool',
        'source_pdfs': 'list[object]',
        'metadata': 'object',
        'expires_in': 'int',
        'delete_custom_files': 'bool'
    }

    attribute_map = {
        'test': 'test',
        'source_pdfs': 'source_pdfs',
        'metadata': 'metadata',
        'expires_in': 'expires_in',
        'delete_custom_files': 'delete_custom_files'
    }

    def __init__(self, test=None, source_pdfs=None, metadata=None, expires_in=None, delete_custom_files=None):  # noqa: E501
        """CombinePdfsData - a model defined in OpenAPI"""  # noqa: E501

        self._test = None
        self._source_pdfs = None
        self._metadata = None
        self._expires_in = None
        self._delete_custom_files = None
        self.discriminator = None

        if test is not None:
            self.test = test
        self.source_pdfs = source_pdfs
        if metadata is not None:
            self.metadata = metadata
        if expires_in is not None:
            self.expires_in = expires_in
        if delete_custom_files is not None:
            self.delete_custom_files = delete_custom_files

    @property
    def test(self):
        """Gets the test of this CombinePdfsData.  # noqa: E501


        :return: The test of this CombinePdfsData.  # noqa: E501
        :rtype: bool
        """
        return self._test

    @test.setter
    def test(self, test):
        """Sets the test of this CombinePdfsData.


        :param test: The test of this CombinePdfsData.  # noqa: E501
        :type: bool
        """

        self._test = test

    @property
    def source_pdfs(self):
        """Gets the source_pdfs of this CombinePdfsData.  # noqa: E501


        :return: The source_pdfs of this CombinePdfsData.  # noqa: E501
        :rtype: list[object]
        """
        return self._source_pdfs

    @source_pdfs.setter
    def source_pdfs(self, source_pdfs):
        """Sets the source_pdfs of this CombinePdfsData.


        :param source_pdfs: The source_pdfs of this CombinePdfsData.  # noqa: E501
        :type: list[object]
        """
        if source_pdfs is None:
            raise ValueError("Invalid value for `source_pdfs`, must not be `None`")  # noqa: E501

        self._source_pdfs = source_pdfs

    @property
    def metadata(self):
        """Gets the metadata of this CombinePdfsData.  # noqa: E501


        :return: The metadata of this CombinePdfsData.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CombinePdfsData.


        :param metadata: The metadata of this CombinePdfsData.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def expires_in(self):
        """Gets the expires_in of this CombinePdfsData.  # noqa: E501


        :return: The expires_in of this CombinePdfsData.  # noqa: E501
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this CombinePdfsData.


        :param expires_in: The expires_in of this CombinePdfsData.  # noqa: E501
        :type: int
        """

        self._expires_in = expires_in

    @property
    def delete_custom_files(self):
        """Gets the delete_custom_files of this CombinePdfsData.  # noqa: E501


        :return: The delete_custom_files of this CombinePdfsData.  # noqa: E501
        :rtype: bool
        """
        return self._delete_custom_files

    @delete_custom_files.setter
    def delete_custom_files(self, delete_custom_files):
        """Sets the delete_custom_files of this CombinePdfsData.


        :param delete_custom_files: The delete_custom_files of this CombinePdfsData.  # noqa: E501
        :type: bool
        """

        self._delete_custom_files = delete_custom_files

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CombinePdfsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
