# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Templatesv2Template(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'expiration_interval': 'str',
        'public_web_form': 'bool',
        'webhook_url': 'str',
        'editable_submissions': 'bool',
        'expire_submissions': 'bool',
        'expire_after': 'float',
        'allow_additional_properties': 'bool',
        'document': 'Templatesv2TemplateDocument',
        'name': 'str',
        'public_submissions': 'bool',
        'slack_webhook_url': 'str',
        'redirect_url': 'str'
    }

    attribute_map = {
        'expiration_interval': 'expiration_interval',
        'public_web_form': 'public_web_form',
        'webhook_url': 'webhook_url',
        'editable_submissions': 'editable_submissions',
        'expire_submissions': 'expire_submissions',
        'expire_after': 'expire_after',
        'allow_additional_properties': 'allow_additional_properties',
        'document': 'document',
        'name': 'name',
        'public_submissions': 'public_submissions',
        'slack_webhook_url': 'slack_webhook_url',
        'redirect_url': 'redirect_url'
    }

    def __init__(self, expiration_interval=None, public_web_form=None, webhook_url=None, editable_submissions=None, expire_submissions=None, expire_after=None, allow_additional_properties=None, document=None, name=None, public_submissions=None, slack_webhook_url=None, redirect_url=None):  # noqa: E501
        """Templatesv2Template - a model defined in OpenAPI"""  # noqa: E501

        self._expiration_interval = None
        self._public_web_form = None
        self._webhook_url = None
        self._editable_submissions = None
        self._expire_submissions = None
        self._expire_after = None
        self._allow_additional_properties = None
        self._document = None
        self._name = None
        self._public_submissions = None
        self._slack_webhook_url = None
        self._redirect_url = None
        self.discriminator = None

        if expiration_interval is not None:
            self.expiration_interval = expiration_interval
        if public_web_form is not None:
            self.public_web_form = public_web_form
        if webhook_url is not None:
            self.webhook_url = webhook_url
        if editable_submissions is not None:
            self.editable_submissions = editable_submissions
        if expire_submissions is not None:
            self.expire_submissions = expire_submissions
        if expire_after is not None:
            self.expire_after = expire_after
        if allow_additional_properties is not None:
            self.allow_additional_properties = allow_additional_properties
        if document is not None:
            self.document = document
        if name is not None:
            self.name = name
        if public_submissions is not None:
            self.public_submissions = public_submissions
        if slack_webhook_url is not None:
            self.slack_webhook_url = slack_webhook_url
        if redirect_url is not None:
            self.redirect_url = redirect_url

    @property
    def expiration_interval(self):
        """Gets the expiration_interval of this Templatesv2Template.  # noqa: E501


        :return: The expiration_interval of this Templatesv2Template.  # noqa: E501
        :rtype: str
        """
        return self._expiration_interval

    @expiration_interval.setter
    def expiration_interval(self, expiration_interval):
        """Sets the expiration_interval of this Templatesv2Template.


        :param expiration_interval: The expiration_interval of this Templatesv2Template.  # noqa: E501
        :type: str
        """
        allowed_values = ["minutes", "hours", "days"]  # noqa: E501
        if expiration_interval not in allowed_values:
            raise ValueError(
                "Invalid value for `expiration_interval` ({0}), must be one of {1}"  # noqa: E501
                .format(expiration_interval, allowed_values)
            )

        self._expiration_interval = expiration_interval

    @property
    def public_web_form(self):
        """Gets the public_web_form of this Templatesv2Template.  # noqa: E501


        :return: The public_web_form of this Templatesv2Template.  # noqa: E501
        :rtype: bool
        """
        return self._public_web_form

    @public_web_form.setter
    def public_web_form(self, public_web_form):
        """Sets the public_web_form of this Templatesv2Template.


        :param public_web_form: The public_web_form of this Templatesv2Template.  # noqa: E501
        :type: bool
        """

        self._public_web_form = public_web_form

    @property
    def webhook_url(self):
        """Gets the webhook_url of this Templatesv2Template.  # noqa: E501


        :return: The webhook_url of this Templatesv2Template.  # noqa: E501
        :rtype: str
        """
        return self._webhook_url

    @webhook_url.setter
    def webhook_url(self, webhook_url):
        """Sets the webhook_url of this Templatesv2Template.


        :param webhook_url: The webhook_url of this Templatesv2Template.  # noqa: E501
        :type: str
        """

        self._webhook_url = webhook_url

    @property
    def editable_submissions(self):
        """Gets the editable_submissions of this Templatesv2Template.  # noqa: E501


        :return: The editable_submissions of this Templatesv2Template.  # noqa: E501
        :rtype: bool
        """
        return self._editable_submissions

    @editable_submissions.setter
    def editable_submissions(self, editable_submissions):
        """Sets the editable_submissions of this Templatesv2Template.


        :param editable_submissions: The editable_submissions of this Templatesv2Template.  # noqa: E501
        :type: bool
        """

        self._editable_submissions = editable_submissions

    @property
    def expire_submissions(self):
        """Gets the expire_submissions of this Templatesv2Template.  # noqa: E501


        :return: The expire_submissions of this Templatesv2Template.  # noqa: E501
        :rtype: bool
        """
        return self._expire_submissions

    @expire_submissions.setter
    def expire_submissions(self, expire_submissions):
        """Sets the expire_submissions of this Templatesv2Template.


        :param expire_submissions: The expire_submissions of this Templatesv2Template.  # noqa: E501
        :type: bool
        """

        self._expire_submissions = expire_submissions

    @property
    def expire_after(self):
        """Gets the expire_after of this Templatesv2Template.  # noqa: E501


        :return: The expire_after of this Templatesv2Template.  # noqa: E501
        :rtype: float
        """
        return self._expire_after

    @expire_after.setter
    def expire_after(self, expire_after):
        """Sets the expire_after of this Templatesv2Template.


        :param expire_after: The expire_after of this Templatesv2Template.  # noqa: E501
        :type: float
        """

        self._expire_after = expire_after

    @property
    def allow_additional_properties(self):
        """Gets the allow_additional_properties of this Templatesv2Template.  # noqa: E501


        :return: The allow_additional_properties of this Templatesv2Template.  # noqa: E501
        :rtype: bool
        """
        return self._allow_additional_properties

    @allow_additional_properties.setter
    def allow_additional_properties(self, allow_additional_properties):
        """Sets the allow_additional_properties of this Templatesv2Template.


        :param allow_additional_properties: The allow_additional_properties of this Templatesv2Template.  # noqa: E501
        :type: bool
        """

        self._allow_additional_properties = allow_additional_properties

    @property
    def document(self):
        """Gets the document of this Templatesv2Template.  # noqa: E501


        :return: The document of this Templatesv2Template.  # noqa: E501
        :rtype: Templatesv2TemplateDocument
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this Templatesv2Template.


        :param document: The document of this Templatesv2Template.  # noqa: E501
        :type: Templatesv2TemplateDocument
        """

        self._document = document

    @property
    def name(self):
        """Gets the name of this Templatesv2Template.  # noqa: E501


        :return: The name of this Templatesv2Template.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Templatesv2Template.


        :param name: The name of this Templatesv2Template.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def public_submissions(self):
        """Gets the public_submissions of this Templatesv2Template.  # noqa: E501


        :return: The public_submissions of this Templatesv2Template.  # noqa: E501
        :rtype: bool
        """
        return self._public_submissions

    @public_submissions.setter
    def public_submissions(self, public_submissions):
        """Sets the public_submissions of this Templatesv2Template.


        :param public_submissions: The public_submissions of this Templatesv2Template.  # noqa: E501
        :type: bool
        """

        self._public_submissions = public_submissions

    @property
    def slack_webhook_url(self):
        """Gets the slack_webhook_url of this Templatesv2Template.  # noqa: E501


        :return: The slack_webhook_url of this Templatesv2Template.  # noqa: E501
        :rtype: str
        """
        return self._slack_webhook_url

    @slack_webhook_url.setter
    def slack_webhook_url(self, slack_webhook_url):
        """Sets the slack_webhook_url of this Templatesv2Template.


        :param slack_webhook_url: The slack_webhook_url of this Templatesv2Template.  # noqa: E501
        :type: str
        """

        self._slack_webhook_url = slack_webhook_url

    @property
    def redirect_url(self):
        """Gets the redirect_url of this Templatesv2Template.  # noqa: E501


        :return: The redirect_url of this Templatesv2Template.  # noqa: E501
        :rtype: str
        """
        return self._redirect_url

    @redirect_url.setter
    def redirect_url(self, redirect_url):
        """Sets the redirect_url of this Templatesv2Template.


        :param redirect_url: The redirect_url of this Templatesv2Template.  # noqa: E501
        :type: str
        """

        self._redirect_url = redirect_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Templatesv2Template):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
