# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.update_submission_data_request_data import UpdateSubmissionDataRequestData  # noqa: E501
from form_api.rest import ApiException


class TestUpdateSubmissionDataRequestData(unittest.TestCase):
    """UpdateSubmissionDataRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSubmissionDataRequestData(self):
        """Test UpdateSubmissionDataRequestData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.update_submission_data_request_data.UpdateSubmissionDataRequestData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
