# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.submission_action import SubmissionAction  # noqa: E501
from form_api.rest import ApiException


class TestSubmissionAction(unittest.TestCase):
    """SubmissionAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionAction(self):
        """Test SubmissionAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.submission_action.SubmissionAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
