# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.template1 import Template1  # noqa: E501
from form_api.rest import ApiException


class TestTemplate1(unittest.TestCase):
    """Template1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplate1(self):
        """Test Template1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.template1.Template1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
