# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.create_folder_data import CreateFolderData  # noqa: E501
from form_api.rest import ApiException


class TestCreateFolderData(unittest.TestCase):
    """CreateFolderData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateFolderData(self):
        """Test CreateFolderData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.create_folder_data.CreateFolderData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
