# coding: utf-8

"""
    API v1

    FormAPI is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.create_submission_data import CreateSubmissionData  # noqa: E501
from form_api.rest import ApiException


class TestCreateSubmissionData(unittest.TestCase):
    """CreateSubmissionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSubmissionData(self):
        """Test CreateSubmissionData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.create_submission_data.CreateSubmissionData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
