#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

echo "Removing trailing whitespace..."
find form_api -name "*.py" -type f -exec sed -E -i 's/[[:space:]]+$//g' {} +

echo "Injecting extensions..."
sed -i "s/from .apis.pdf_api import PDFApi/\
from .apis.pdf_api import PDFApi\nfrom .apis.client import Client/" \
form_api/__init__.py

cp extensions/form_api/apis/client.py form_api/apis
